### PR TITLE
Fixes #38049 - Fix downstream documentation link for discovery

### PR DESCRIPTION
**Pull request by girijaasoni**
Fix only for the downstream

### CODE REVIEW

**Comment by evgeni** [comment]
The develop branch doesn't need to support 6.25 and older, so you can just update the link unconditionally

**Comment by girijaasoni** [comment]
> The develop branch doesn't need to support 6.25 and older, so you can just update the link unconditionally

6.16 and further needs no change, so does that mean we don't need to fix the issue for the prior versions?

**Comment by evgeni** [comment]
If you want to fix something for 6.15, you can open a PR against the 13.2-stable branch

**Comment by girijaasoni** [comment]
Closing this PR as the issue is not reproducible for 6.16 and further. We don't need a fix for previous versions. Thanks @evgeni

**Pull request closed without merging**
