### PR TITLE
Release 14.0.0

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Should this be 14.0 since it requires Foreman 3.13+?

**Comment by evgeni** [comment]
It could, we've not done semver properly here in the past.
(Also, theme releases are more oriented on Satellite releases, not Foreman ones, even if they sometimes match :D)

**Comment by ekohl** [comment]
We could bump it up to 17 if you want ;)

**Comment by evgeni** [comment]
I'd prefer not to -- this would tie the version to a hypothetical Satellite version, which might or might not be true in future.

**Pull request merged**
