### PR TITLE
Update title URL paths - add 'by'

### PR DESCRIPTION
**Pull request by Lennonka**
Needed because of https://github.com/theforeman/foreman-documentation/pull/3185

Meant for Sat 6.16

### CODE REVIEW

**Comment by Lennonka** [comment]
I'm not sure if any other files require changes. If they do, please let me know.

**Comment by ShimShtein** [comment]
Let's wait for the latest TOC to be generated. It would be available in the https://github.com/RedHatSatellite/foreman_theme_satellite/tree/toc_update branch.
Then the procedure would be to import the new TOC commit into this PR and fix the broken links. We will be able to actually test the change against the new TOC.

Also, please rebase this PR once https://github.com/RedHatSatellite/foreman_theme_satellite/pull/65 gets in.

**Comment by Lennonka** [comment]
Rebased.

**Comment by ShimShtein** [comment]
Now we see that the links checker fails for the old TOC. We need to cherry-pick the TOC version with the new links and then we will see the tests pass.

**Comment by Lennonka** [comment]
@ShimShtein Yeah, but where from? The `toc_update` branch doesn't exist now

**Comment by girijaasoni** [comment]
looks fine to me as per my understanding

**Comment by ShimShtein** [comment]
I have merged the latest TOC, that's why the branch removed. I think the new structure is not yet available downstream.

**Comment by Lennonka** [comment]
Cherrypicked commit from `toc_update` and rebased again.

**Comment by ShimShtein** [comment]
Merged, thanks @Lennonka!

**Pull request merged**
